/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.soeu.view;

import com.soeu.entities.Aluno;
import com.soeu.services.AlunoService;

/**
 *
 * @author Anderson
 */
public class MinhaContaTela extends javax.swing.JFrame {
    
    private Aluno alunoLogado;
    
    public MinhaContaTela(Aluno aluno) {
    initComponents();
    this.alunoLogado = aluno;
}
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MinhaContaTela.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public MinhaContaTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Dados Cadastrais");

        jButton1.setText("Visualizar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Editar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Excluir");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

 try {
        String novoNome = javax.swing.JOptionPane.showInputDialog(this, "Novo nome:", alunoLogado.getNome());

        String novoEmail = javax.swing.JOptionPane.showInputDialog(this, "Novo email:", alunoLogado.getEmail());
        String novoCurso = javax.swing.JOptionPane.showInputDialog(this, "Novo curso:", alunoLogado.getCurso());
        String novaSenha = javax.swing.JOptionPane.showInputDialog(this, "Nova senha:", alunoLogado.getSenha());

        if (novoEmail == null || novoCurso == null || novaSenha == null) {
            return;
        }
        
        alunoLogado.setNome(novoNome);
        alunoLogado.setEmail(novoEmail);
        alunoLogado.setCurso(novoCurso);
        alunoLogado.setSenha(novaSenha);

        com.soeu.services.AlunoService alunoService = new com.soeu.services.AlunoService();
        alunoService.atualizar(alunoLogado);

        javax.swing.JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso!");

    } catch (RuntimeException e) {
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    int resposta = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Tem certeza que deseja excluir sua conta?",
            "Confirmar exclusão",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (resposta != javax.swing.JOptionPane.YES_OPTION) {
        return;
    }

    try {
        com.soeu.services.AlunoService alunoService = new com.soeu.services.AlunoService();

        alunoService.excluir(alunoLogado.getMatricula());

        javax.swing.JOptionPane.showMessageDialog(this, "Conta excluída com sucesso!");

        new LoginTela().setVisible(true);
        this.dispose();

    } catch (RuntimeException e) {
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
    }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

try {
        AlunoService alunoService = new AlunoService();

        Aluno alunoAtualizado =
                alunoService.buscarNaViewPorId(alunoLogado.getMatricula());

        if (alunoAtualizado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Aluno não encontrado.");
            return;
        }

        javax.swing.JOptionPane.showMessageDialog(this,
            "Nome: " + alunoAtualizado.getNome() +
            "\nEmail: " + alunoAtualizado.getEmail() +
            "\nCurso: " + alunoAtualizado.getCurso() +
            "\nIRA: " + alunoAtualizado.getIra() +
            "\nPeríodo: " + alunoAtualizado.getPeriodo() +
            "\nData de nascimento: " + alunoAtualizado.getDataNascimento()
        );

    } catch (RuntimeException e) {
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MinhaContaTela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
