/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.soeu.view;
import com.soeu.entities.Aluno;
import com.soeu.entities.Disciplina;
import com.soeu.entities.Material;
import com.soeu.services.DisciplinaService;
import com.soeu.services.MaterialService;

import java.io.File;
import java.nio.file.Files;
import java.util.List;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Anderson
 */
public class TelaMaterias extends javax.swing.JFrame {
    
    private Aluno alunoLogado;
    private File arquivoSelecionado;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMaterias.class.getName());

    /**
     * Creates new form TelaMaterias
     */
    public TelaMaterias(Aluno aluno) {
    initComponents();
    this.alunoLogado = aluno;

    carregarDisciplinas();
}
 
 private void carregarMateriais() {
    try {
        Disciplina disciplina = (Disciplina) jComboBox1.getSelectedItem();

        if (disciplina == null) {
            return;
        }

        MaterialService materialService = new MaterialService();

        List<Material> materiais =
                materialService.readByDisciplina(disciplina.getCodigo());

        DefaultTableModel modelo =
                (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);

        for (Material material : materiais) {
            modelo.addRow(new Object[]{
                material.getTipo(),
                material.getNomeArquivo(),
                material.getLink()
            });
        }

    } catch (RuntimeException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}   
 
private void carregarDisciplinas() {
    try {
        DisciplinaService disciplinaService = new DisciplinaService();

        jComboBox1.removeAllItems();

        for (Disciplina disciplina : disciplinaService.listarTodas()) {
            jComboBox1.addItem(disciplina);
        }

    } catch (RuntimeException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btVoltar = new javax.swing.JButton();
        btEscolher = new javax.swing.JButton();
        btVisualizar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Materiais");

        jLabel2.setText("Disciplina:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tipo", "Nome Arquivo", "Link"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(this::btVoltarActionPerformed);

        btEscolher.setText("Escolher Arquivo");
        btEscolher.addActionListener(this::btEscolherActionPerformed);

        btVisualizar.setText("Listar");
        btVisualizar.addActionListener(this::btVisualizarActionPerformed);

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(this::btExcluirActionPerformed);

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(this::btSalvarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEscolher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btVisualizar)
                        .addGap(12, 12, 12)
                        .addComponent(btExcluir)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVoltar)
                    .addComponent(btEscolher)
                    .addComponent(btSalvar)
                    .addComponent(btVisualizar)
                    .addComponent(btExcluir))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEscolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEscolherActionPerformed

    JFileChooser chooser = new JFileChooser();

    int resultado = chooser.showOpenDialog(this);

    if (resultado == JFileChooser.APPROVE_OPTION) {
        arquivoSelecionado = chooser.getSelectedFile();

        JOptionPane.showMessageDialog(
            this,
            "Arquivo selecionado: " + arquivoSelecionado.getName()
        );
    }

    }//GEN-LAST:event_btEscolherActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

    try {
        Disciplina disciplina = (Disciplina) jComboBox1.getSelectedItem();

        if (disciplina == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma disciplina.");
            return;
        }

        if (arquivoSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um arquivo.");
            return;
        }

        byte[] arquivoBytes = Files.readAllBytes(arquivoSelecionado.toPath());

        Material material = new Material();

        material.setTipo("Arquivo");
        material.setLink("");
        material.setNomeArquivo(arquivoSelecionado.getName());
        material.setArquivo(arquivoBytes);
        material.setDisciplina(disciplina);

        MaterialService materialService = new MaterialService();
        materialService.create(material);

        JOptionPane.showMessageDialog(this, "Material salvo com sucesso!");

        carregarMateriais();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
        
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarActionPerformed
    carregarMateriais();
    }//GEN-LAST:event_btVisualizarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
    new TelaCurso(alunoLogado).setVisible(true);
    this.dispose();    }//GEN-LAST:event_btVoltarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        JOptionPane.showMessageDialog(this, "Exclusão de material será implementada depois.");    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(() -> new TelaMaterias().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEscolher;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVisualizar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
